---
# Init Guac DBMS
- name: Configure and initialize Guac DBMS
  ansible.builtin.include_tasks: guac/init.yml

- name: Provision Guac collectsub
  ansible.builtin.include_tasks: guac/guac_collectsub.yml

- name: Provision Guac graphql
  ansible.builtin.include_tasks: guac/guac_graphql.yml
